### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by budimanjojo** [berberman/nvfetcher#116]
Hello, building the package is failing with this error:
```
error: builder for '/nix/store/7qlz44yq5kifav7g1mhmia7as3qzh8vz-python3.11-nvchecker-2.12.drv' failed with exit code 1;
       last 10 log lines:
       > ERROR tests/test_regex.py::test_regex_post_json
       > ERROR tests/test_regex.py::test_regex_post_json2
       > ERROR tests/test_substitute.py::test_substitute_prefix
       > ERROR tests/test_substitute.py::test_substitute_prefix_missing_ok
       > ERROR tests/test_substitute.py::test_substitute_regex
       > ERROR tests/test_substitute.py::test_substitute_regex_missing_ok
       > ERROR tests/test_substitute.py::test_substitute_regex_empty_to_pattern
       > ERROR tests/test_substitute.py::test_substitute_prefix_has_higher_priority
       > =========== 2 passed, 13 skipped, 74 deselected, 26 errors in 0.66s ============
       > /nix/store/3qnm3nwjajgqa771dmi2dnwxrw0kzq5m-stdenv-linux/setup: line 1578: pop_var_context: head of shell_variables not a function context
```

Thanks before!

**Comment by berberman** [comment]
Maybe already fixed by https://github.com/NixOS/nixpkgs/pull/291229 ?

**Comment by budimanjojo** [comment]
I'm consuming the package from this repo `flake.nix` file at `packages.default`. Not sure if I'm also affected by the `nixpkgs` changes. I also tried using the `nixpkgs` provided by this repo's flake and build still failing.

**Comment by wrvsrx** [comment]
maybe you use nixpkgs.follows in your flake.

**Comment by budimanjojo** [comment]
@wrvsrx I tried with and without follows. I think it's because of `nvchecker` package that's being used to build `nvfetcher` like @berberman mentioned above. I'll just wait until that PR got into unstable and close this issue.

**Comment by wrvsrx** [comment]
@budimanjojo `nix build github:berberman/nvfetcher/367e2eaa92d8f5133c2c5ac03a80c0cf25f301b8` just works (367e2eaa92d8f5133c2c5ac03a80c0cf25f301b8 is the latest commit now). This issue only occurs in nixpkgs since nixpkgs have updated some dependency. You might set some follows or overlays, maybe you can provide a minimal example that can reproducbe this issue.

**Comment by berberman** [comment]
I think this issue has nothing to do with nvfetcher itself, so I'm closing it.
